### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by keane-k1** [LISTENAI/lisa-plugin-btest#1]
1. 需要一个创建测试工程的命令
2. 没有usb2xxx 的时候，应该也可用（纯日志、or Other）；
3. shell 被btest接管，对固件运行状态，没办法实时的查看，需要有一个方式，可以把 shell log 实时转发，甚么是shell实时转发；
4. 如果使用原有的一些shell，比如 lisa_player 模块本身提供了一些shell命令；

**Comment by xingrz** [comment]
done
