### ISSUE TITLE
README中的shell.match的使用说明缺少一个常用的timeout参数，建议加上。

### ISSUE THREAD

**Issue by SawXu** [LISTENAI/lisa-plugin-btest#18]
README中的shell.match的使用说明缺少一个常用的timeout参数，建议加上。
目前需要在源码中查找match的原型或者依赖代码提示才能知道。
![image](https://user-images.githubusercontent.com/8655709/172973123-e1dc0735-cc18-4827-8cd0-d1226e2d19f2.png)

**Comment by chh7872** [comment]
此问题较早前已经处理，issue close
