### ISSUE TITLE
应用级btest使用需求

### ISSUE THREAD

**Issue by monsterboom** [LISTENAI/lisa-plugin-btest#5]
1、不需要用户本地的python环境。
      ~/.listenai/lisa-btest
      btest 内置多一个 python
2、posinstall 安装好内置 requirement
3、dm:init 添加参数，输出路径
4、run 添加参数，带上device.yml路径，btest.yml路径
5、新增 btest init 命令，初始化 btest.yml，可带输出路径参数

**Comment by chh7872** [comment]
- [x] 1、不需要用户本地的python环境。
~/.listenai/lisa-btest
btest 内置多一个 python
- [x] 2、posinstall 安装好内置 requirement
- [x] 3、dm:init 添加参数，输出路径
- [x] 4、run 添加参数，带上~~device.yml路径~~，btest.yml路径
device-map.yml路径暂时没办法通过btest run传入，想办法ing...
- [x] 5、新增 btest init 命令，初始化 btest.yml，可带输出路径参数

**Comment by chh7872** [comment]
一些使用说明：
1. btest现在依赖${homedir}/.listenai/lisa-btest/framework/python/venv中的python
2. 在安装btest的时候，会自动pip install parse pyocd pyserial pytest pyyaml
3. 用户可通过lisa btest dm:init --output="path/to/device-map"来指定输出device-map.yml的路径
4. lisa btest run --with-config="path/to/lisa-btest.yml"来指定lisa-btest.yml的路径
    但需要注意的是，device-map.yml路径需要在python test case file中自行调整
5. lisa btest init --prefix="path/to/btest/project/dir"可在"path/to/btest/project/dir"中生成用户所需最简单的btest工程环境
